[tool.poetry]
name = "vocal-topic"
version = "0.1.0"
description = ""
authors = ["Yuya Yamamoto <s2130507@s.tsukuba.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

